### ISSUE TITLE
Class constructor ReducerClass cannot be invoked without 'new'

### ISSUE THREAD

**Issue by vatsalm-scaleup** [keenondrums/reducer-class#1]
when trying to run the create-react-app (typescript) using ts-node it throws!

**Comment by fxlrnrpt** [comment]
@vatsalm-scaleup could you provide a code sample to reproduce?

**Comment by vatsalm-scaleup** [comment]
@aigoncharov I figured it, it was tsconfig issue, thanks

**Comment by fxlrnrpt** [comment]
@vatsalm-scaleup welcome
